### Create Article
POST localhost:7075/v1/article/moderator
Authorization: Bearer
Content-Type: application/json

{
  "title": "DAXSHAT XABAR😨",
  "description": "TELEVIDENIYA QAYERGA QARAYABTI",
  "content": "JUNIOR DASTURCHI ISHGA KIRIB KETTI",
  "regionId": 1,
  "categoryList": [
    {"id" : 1},
    {"id" : 2}
  ],
  "sectionList": [
    {"id": 1}
  ]
}

###Update
PUT localhost:7075/v1/article/moderator/ca53c14a-f08c-4104-96b2-81ed96dab139
Authorization: Bearer
Content-Type: application/json

{
  "title": "DAXSHAT XABAR😨",
  "description": "TLIVIDENIYA QERA QARAYABTI",
  "content": "JUNIOR DASTURCHI ISHGA KIRIB KETTI",
  "regionId": 1,
  "categoryList": [
    {"id" : 1}
  ],
  "sectionList": [
    {"id": 1},
    {"id": 2}
  ]
}

### Delete article
DELETE localhost:7075/v1/article/moderator/
Authorization: Bearer

### Change Status
PUT localhost:7075/v1/article/publisher/status
Authorization: Bearer
Content-Type: application/json

{

}
