### Registration
POST localhost:7075/v1/auth/registration
Content-Type: application/json

{
  "name": "Umidjon",
  "surname": "Makhmudov",
  "username": "998500781179",
  "password": "12345"
}

### Login
POST localhost:7075/v1/auth/login
Content-Type: application/json

{
  "username": "oda@gmail.com",
  "password": "2345"
}
