### Get Categories
GET localhost:7075/v1/category

### Create category
POST localhost:7075/v1/category
Content-Type: application/json

{
  "orderNumber": 1,
  "key": "farm",
  "nameUz": "Ferma",
  "nameRu": "Ферма",
  "nameEn": "Farm"
}

### Update Category
PUT localhost:7075/v1/category/1
Content-Type: application/json

{
  "orderNumber": 3,
  "key": "world",
  "nameUz": "Jahon",
  "nameRu": "Мир",
  "nameEn": "World"
}

### Delete Category
DELETE localhost:7075/v1/category/4

### Get By Language
GET localhost:7075/v1/category/lang
Accept-Language: EN