### Create
POST localhost:7075/v1/profile
Content-Type: application/json

{
  "name": "Elbek",
  "surname": "Kiselev",
  "username": "elka@gmail.com",
  "password": "2345",
  "roleList": [
    "ROLE_USER"
  ]
}

### Get All
GET localhost:7075/v1/profile/page?page=1&size=3

### Login
POST localhost:7075/v1/profile/login
Content-Type: application/json

{
  "username": "+998900031904",
  "password": "190204"
}


### Update
PUT localhost:7075/v1/profile/update
Content-Type: application/json

{
  "name": "Toshmat",
  "surname": "Toshmatov",
  "username": "toshmat@gmail.com",
  "rolesList": [
    "ROLE_USER",
    "ROLE_MODERATOR"
  ]
}