### Create section
POST localhost:7075/v1/section/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX1VTRVIiLCJST0xFX0FETUlOIiwiUk9MRV9NT0RFUkFUT1IiXSwidXNlcm5hbWUiOiJlc2htYXQzQGdtYWlsLmNvbSIsInN1YiI6ImVzaG1hdDNAZ21haWwuY29tIiwiaWF0IjoxNzUwNDM1OTM1LCJleHAiOjE3NTA1MjIzMzV9.siQLghkHcfpSfL7frAAMhnGNUu0vhw1WkA-I2Y8959I
Content-Type: application/json

{
  "orderNumber": 4,
  "nameUz": "Asosiy 4",
  "nameRu": "Основной 4",
  "nameEn": "Main 4",
  "key": "main4"
}


### Update section
PUT localhost:7075/api/v1/section/admin/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiJiaWdtYW5nY29tQGdtYWlsLmNvbSIsInN1YiI6ImJpZ21hbmdjb21AZ21haWwuY29tIiwiaWF0IjoxNzUwMzAyODkxLCJleHAiOjE3NTAzODkyOTF9.jiApspABtlGP2x8zYvQkRnqqvl16o2VOIv_p6-8-Z9eQb0R5DsN3sjpWTADpijxEK0FvTVhWFe7iRRV9N9CwAA

{
  "orderNumber": 1,
  "nameUz": "Asosiy 11",
  "nameRu": "Основной 11",
  "nameEn": "Main 11",
  "sectionKey": "main1"
}


### Delete category
DELETE localhost:7075/api/v1/section/admin/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiJiaWdtYW5nY29tQGdtYWlsLmNvbSIsInN1YiI6ImJpZ21hbmdjb21AZ21haWwuY29tIiwiaWF0IjoxNzUwMzAyODkxLCJleHAiOjE3NTAzODkyOTF9.jiApspABtlGP2x8zYvQkRnqqvl16o2VOIv_p6-8-Z9eQb0R5DsN3sjpWTADpijxEK0FvTVhWFe7iRRV9N9CwAA


### Get region list
GET localhost:7075/api/v1/section/admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiJiaWdtYW5nY29tQGdtYWlsLmNvbSIsInN1YiI6ImJpZ21hbmdjb21AZ21haWwuY29tIiwiaWF0IjoxNzUwMzAyODkxLCJleHAiOjE3NTAzODkyOTF9.jiApspABtlGP2x8zYvQkRnqqvl16o2VOIv_p6-8-Z9eQb0R5DsN3sjpWTADpijxEK0FvTVhWFe7iRRV9N9CwAA


### Get section by lang
GET localhost:7075/api/v1/section/lang
Accept-Language: EN
